#!/bin/bash

module load mricron/20181125
module load fsl/6.0.1

set -e 

####Get the information
echo -n "Enter the dicom directory (e.g. /u/project/jfeusner/data/VISUAL_MOD/ANALYSIS_VISMOD/GROUP/VM_TASK/angel_analysis/raw_mri_data/bids/dicom/bdd_group): "
read dcmdir

echo -n "Enter the nifti directory (e.g. /u/project/jfeusner/data/VISUAL_MOD/ANALYSIS_VISMOD/GROUP/VM_TASK/angel_analysis/raw_mri_data/bids/nifti/test): "
read niidir

echo -n "Enter the subject ID (can be more than one subject ID e.g. 5001 5002 5003): "
read subjects

####Double check the paths
echo "Dicom directory is ${dcmdir}"
echo "Nifti directory is ${niidir}"

####Define software directory
softwaredir=/u/project/jfeusner/data/SOFTWARE/bin

###Create dataset_description.json
${softwaredir}/jo -p "Name"="CON Visual Modulation and Rest Dataset" "BIDSVersion"="1.0.2" >> ${niidir}/dataset_description.json

for subj in $subjects; do
	echo "Processing subject $subj"

	####Anatomical Organization####
	###Create structure
	mkdir -p ${niidir}/sub-${subj}/anat

	###Convert dcm to nii
	#Only convert the Dicom folder anat
	cd ${dcmdir}/${subj}
	for direcs in *MPRAGE*; do
		dcm2niix -b y -o ${niidir}/sub-${subj} -f ${subj}_%p_%s ${dcmdir}/${subj}/${direcs}
	done

	#Changing directory into the subject folder
	cd ${niidir}/sub-${subj}

	###Change filenames
	##Rename anat files
	#Example filename: 5015_t1_mprage_sag_p3_iso_8
	#BIDS filename: sub-5015_T1w
	#Capture the number of anat files to change
	anatfiles=$(ls -1 *mprage* | wc -l)
	for ((i=1;i<=${anatfiles};i++)); do
		Anat=$(ls *mprage*) #This is to refresh the Anat variable, if this is not in the loop, each iteration a new "No such file or directory error", this is because the filename was changed. 
		tempanat=$(ls -1 $Anat | sed '1q;d') #Capture new file to change
		tempanatext="${tempanat##*.}"
		tempanatfile="${tempanat%.*}"
		mv --backup=numbered ${tempanatfile}.${tempanatext} sub-${subj}_T1w.${tempanatext}
		echo "${tempanat} changed to sub-${subj}_T1w.${tempanatext}"
	done

	###Organize files into folders
	for files in $(ls sub*); do 
		Orgfile="${files%.*}"
		Orgext="${files##*.}"
		Modality=$(echo $Orgfile | rev | cut -d '_' -f1 | rev)
		if [ $Modality == "T1w" ]; then
			mv ${Orgfile}.${Orgext} anat
		fi 
	done

	#Rename all *.gz to *.nii.gz
	cd ${niidir}/sub-${subj}/anat
	for niifiles in *.gz; do
		mv -- "$niifiles" "${niifiles%.gz}.nii.gz"
	done

	####Diffusion Organization####
	#Create subject folder 
	mkdir -p ${niidir}/sub-${subj}/dwi

	###Convert dcm to nii
	#Converting the two diffusion Dicom directories
	cd ${dcmdir}/${subj}
	for direcs in *DWI*; do
		dcm2niix -b y -o ${niidir}/sub-${subj} -f ${subj}_%p_%s ${dcmdir}/${subj}/${direcs}
	done

	#Changing directory into the subject folder
	cd ${niidir}/sub-${subj}

	#change dwi
	#Example filename: 5015_DWI_dir99_AP_7
	#BIDS filename: sub-5015_dwi
	#difffiles will capture how many filenames to change
	difffiles=$(ls -1 *DWI* | wc -l)
	for ((i=1;i<=${difffiles};i++)); do
		Diff=$(ls *DWI*) #This is to refresh the diff variable, same as the cases above. 
		tempdiff=$(ls -1 $Diff | sed '1q;d')
		tempdiffext="${tempdiff##*.}"
		tempdifffile="${tempdiff%.*}"
		mv --backup=numbered ${tempdifffile}.${tempdiffext} sub-${subj}_dwi.${tempdiffext}
		echo "$tempdiff changed to sub-${subj}_dwi.${tempdiffext}"
	done
	
	###Organize files into folders
	for files in $(ls sub*); do 
		Orgfile="${files%.*}"
		Orgext="${files##*.}"
		Modality=$(echo $Orgfile | rev | cut -d '_' -f1 | rev)
		if [ $Modality == "dwi" ]; then
			mv ${Orgfile}.${Orgext} dwi
		fi
	done
	
	#Rename all *.gz to *.nii.gz
	cd ${niidir}/sub-${subj}/dwi
	for niifiles in *.gz; do
		mv -- "$niifiles" "${niifiles%.gz}.nii.gz"
	done	

	####Functional Organization####
	#Create subject folder
	mkdir -p ${niidir}/sub-${subj}/func

	###Convert dcm to nii
	cd ${dcmdir}/${subj}
	for direcs in VIS_MOD_1_* VIS_MOD_2_* VIS_MOD_3_* REST*; do
		dcm2niix -b y -o ${niidir}/sub-${subj} -f ${subj}_%p_%s ${dcmdir}/${subj}/${direcs}
	done

	#Changing directory into the subject folder
	cd ${niidir}/sub-${subj}

	##Rename func files
	#Break the func down into each task
	#VIS_MOD task
	#Example filename: 5015_VIS_MOD_1_Nat_tilt-12_5
	#BIDS filename: sub-5015_task-VISMOD1Nat_bold
	#Capture the number of files to change
	vismodfiles=$(ls -1 *VIS_MOD* | wc -l)
	for ((i=1;i<=${vismodfiles};i++)); do
		vismod=$(ls *VIS_MOD*) #This is to refresh the vismod variable, same as the Anat case
		tempvismod=$(ls -1 $vismod | sed '1q;d') #Capture new file to change
		tempvismodext="${tempvismod##*.}"
		tempvismodfile="${tempvismod%.*}"
		taskname=$(echo $tempvismodfile | awk -F'[_]' '{print $2$3$4$5}')
		mv --backup=numbered ${tempvismodfile}.${tempvismodext} sub-${subj}_task-${taskname}_bold.${tempvismodext}
		echo "${tempvismodfile}.${tempvismodext} changed to sub-${subj}_task-${taskname}_bold.${tempvismodext}"
	done

	#Rest
	#Example filename: 5015_Rest_MB8_1_9
	#BIDS filename: sub-5015_task-rest_bold
	#Capture the number of files to change
	restfiles=$(ls -1 *Rest* | wc -l)
	for ((i=1;i<=${restfiles}/2;i++)); do
		restnii=$(ls *Rest*nii*)
		temprestnii=$(ls -1 $restnii | sed '1q;d')
		tp=`fslnvols $temprestnii`
		for ((j=1;j<=2;j++)); do
			rest=$(ls *Rest*) #This is to refresh the rest variable, same as the Anat case
			temprest=$(ls -1 $rest | sed '1q;d') #Capture new file to change
			temprestext="${temprest##*.}"
			temprestfile="${temprest%.*}"
			mv --backup=numbered ${temprestfile}.${temprestext} sub-${subj}_task-rest_acq-${tp}TP_bold.${temprestext}
			echo "${temprestfile}.${temprestext} changed to sub-${subj}_task-rest_acq-${tp}TP_bold.${temprestext}"
		done
	done
	
	###Organize files into folders
	for files in $(ls sub*); do 
		Orgfile="${files%.*}"
		Orgext="${files##*.}"
		Modality=$(echo $Orgfile | rev | cut -d '_' -f1 | rev)
		if [ $Modality == "bold" ]; then
			mv ${Orgfile}.${Orgext} func
		fi
	done
	
	#Handle duplicate rest files
	if ls *rest*~* 1> /dev/null 2>&1; then
		for file in *rest*~*; do
			dupfile="${file%.*}"
			dupext="${file##*.}"
			dupnum=$(echo $file | awk -F'[~]' '{print $2}')
			mv $file ${file//.${dupext}/}
			mv $dupfile ${dupfile//TP/TP${dupnum}}
		done
		mv sub*TP* func
		cd func
		((newnum=$dupnum+1))
		for file in *TP_*; do
			mv $file ${file//TP/TP${newnum}}
		done
	fi
	
	#Rename all *.gz to *.nii.gz
	cd ${niidir}/sub-${subj}/func
	rename .gz .nii.gz *.gz*	

	###Check func json for required fields
	#Required fields for func: 'RepetitionTime','VolumeTiming' or 'SliceTiming', and 'TaskName'
	#capture all jsons to test
	cd ${niidir}/sub-${subj}/func #Go into the func folder
	for funcjson in $(ls *.json*); do 

		#Repeition Time exist?
		repeatexist=$(cat ${funcjson} | ${softwaredir}/jq '.RepetitionTime')
		if [[ ${repeatexist} == "null" ]]; then   
			echo "${funcjson} doesn't have RepetitionTime defined"
		else
			echo "${funcjson} has RepetitionTime defined"
		fi

		#VolumeTiming or SliceTiming exist?
		#Constraint SliceTiming can't be great than TR
		volexist=$(cat ${funcjson} | ${softwaredir}/jq '.VolumeTiming')
		sliceexist=$(cat ${funcjson} | ${softwaredir}/jq '.SliceTiming')
		if [[ ${volexist} == "null" && ${sliceexist} == "null" ]]; then
			echo "${funcjson} doesn't have VolumeTiming or SliceTiming defined"
		else
			if [[ ${volexist} == "null" ]]; then
				echo "${funcjson} has SliceTiming defined"
				#Check SliceTiming is less than TR
				sliceTR=$(cat ${funcjson} | ${softwaredir}/jq '.SliceTiming[] | select(.>="$repeatexist")')
				if [ -z ${sliceTR} ]; then
					echo "All SliceTiming is less than TR" #The slice timing was corrected in the newer dcm2niix version called through command line
				else
					echo "SliceTiming error"
				fi
			else
				echo "${funcjson} has VolumeTiming defined"
			fi
		fi

		#Does TaskName exist?
		taskexist=$(cat ${funcjson} | ${softwaredir}/jq '.TaskName')
		if [ "$taskexist" == "null" ]; then
			jsonname="${funcjson%.*}"
			taskfield=$(echo $jsonname | cut -d '_' -f2 | cut -d '-' -f2)
			${softwaredir}/jq '. |= . + {"TaskName":"'${taskfield}'"}' ${funcjson} > tasknameadd.json
			rm ${funcjson}
			mv tasknameadd.json ${funcjson}
			echo "TaskName was added to ${jsonname} and matches the tasklabel in the filename"
		else
			Taskquotevalue=$(${softwaredir}/jq '.TaskName' ${funcjson})
			Taskvalue=$(echo $Taskquotevalue | cut -d '"' -f2)	
			jsonname="${funcjson%.*}"
			taskfield=$(echo $jsonname | cut -d '_' -f2 | cut -d '-' -f2)
			if [ $Taskvalue == $taskfield ]; then
				echo "TaskName is present and matches the tasklabel in the filename"
			else
				echo "TaskName and tasklabel do not match"
			fi
		fi

	done
done
